name: EpicChat
version: 1.0
main: me.arace863.epicchat.EpicChat
authors: [ ARace863 ]
description: EpicChat is a plugin that will add many features to make your chat more user friendly the way you want it to be!
website: https://arace863.github.io/Website/